domains_to_block:
  - twitter.com
  - www.twitter.com
  - instagram.com
  - www.instagram.com
  - api.twitter.com
  - x.com
  - www.x.com
  - api.x.com
  - youtube.com
  - www.youtube.com
  - studio.youtube.com
  - whatsapp.com
  - web.whatsapp.com
  - gmail.com
  - www.gmail.com
  - app.convertkit.com
  - slack.com
  - discord.com
