domains_to_block:
  - twitter.com
  - www.twitter.com
  - instagram.com
  - www.instagram.com
  - api.twitter.com
  - x.com
  - www.x.com
  - api.x.com
  - youtube.com
  - www.youtube.com
  - studio.youtube.com
  - whatsapp.com
  - web.whatsapp.com
  - gmail.com
  - www.gmail.com
  - app.convertkit.com
  - slack.com
  - discord.com

bookmarks_api_url: "https://bookmarks.alexvyber.dev/bookmarks"

repos:
  - "@alexvyber/doingstuff"
  - "@alexvyber/repos/vyber-cli"
  - "@alexvyber/repos/spoon"
  - "@alexvyber/repos/genstuff"
  - "@alexvyber/repos/boring"
  - "@alexvyber/repos/blank"
  - "@alexvyber/repos/classic"
  - "@alexvyber/repos/cvax"
  - "@alexvyber/repos/genstuff"
  - "@alexvyber/repos/katzen-csv"
  - "@alexvyber/repos/math-not-meth"
  - "@alexvyber/repos/nails"
  - "@alexvyber/repos/shmoodle-meet"
  - "@alexvyber/repos/stw"
  - "@alexvyber/repos/dragonfly-eld/api"
  - "@alexvyber/repos/dragonfly-eld/cms"
  - "@alexvyber/repos/dragonfly-eld/marketing"
  - "@alexvyber/repos/dragonfly-eld/mobile"
  - "@alexvyber/repos/dragonfly-eld/web"
  - "REPOS/node"
  - "REPOS/fastify"
  - "REPOS/DefinitelyTyped"
  - "REPOS/pino"
  - "REPOS/v8"
  - "REPOS/zustand"
  - "REPOS/vite"
  - "REPOS/v8js"
  - "REPOS/strapi"
  - "REPOS/react"
  - "dotfiles"